# Generated by Django 5.2.4 on 2025-08-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(
                max_length=20,
                unique=True,
                editable=False
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('SUCCESS', 'Success'),
                    ('FAILED', 'Failed')
                ],
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='app.rentalrequest'
            ),
        ),
    ]
