# Generated by Django 5.2.4 on 2025-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
