# Generated by Django 5.2.4 on 2025-11-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_cartitem_end_date_cartitem_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
