# Generated by Django 5.2.4 on 2025-11-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="patient_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="patient_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
