# Generated by Django 5.2.4 on 2025-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_rentalrequest_patient_name_userdetail_patient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rentalrequest",
            name="delivery_option",
            field=models.CharField(
                blank=True,
                choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                max_length=20,
                null=True,
            ),
        ),
    ]
