# Generated by Django 5.2.4 on 2025-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_rentalrequest_delivery_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="is_return_requested",
            field=models.BooleanField(default=False),
        ),
    ]
