# Generated by Django 5.2.4 on 2025-12-25 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_rentalrequest_is_return_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
