# Generated by Django 5.2.4 on 2025-12-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_rentalrequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="rental_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="app.rentalrequest",
            ),
        ),
    ]
