# Generated by Django 5.2.4 on 2025-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_payment_order_id_alter_payment_rental_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
