# Generated by Django 5.2.4 on 2025-12-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_rentalrequest_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
