# Generated by Django 5.2.4 on 2026-01-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_rentalrequest_is_returned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="aadhar",
        ),
        migrations.AddField(
            model_name="userdetail",
            name="id_proof_number",
            field=models.CharField(default="N/A", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdetail",
            name="id_proof_type",
            field=models.CharField(default="Aadhaar", max_length=20),
            preserve_default=False,
        ),
    ]
