# Generated by Django 5.2.4 on 2026-01-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_remove_userdetail_aadhar_userdetail_id_proof_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalrequest",
            name="extended_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
