# Generated by Django 5.2.4 on 2026-01-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_rentalrequest_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="return_pickup_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
