# Generated by Django 5.2.4 on 2026-01-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_rentalrequest_return_pickup_charge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalrequest",
            name="receipt",
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking Receipt"),
                            ("return", "Return Receipt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="receipts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rental_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="app.rentalrequest",
                    ),
                ),
            ],
        ),
    ]
