# Generated by Django 5.2.4 on 2026-04-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_remove_rentalrequest_receipt_receipt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RentalItem",
            new_name="Inventory",
        ),
    ]
