# Generated by helper - create Item model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("app", "0042_merge_rename_rentalitem_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donation', models.BooleanField(default=False)),
                ('donor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('donor_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
