# Generated by Django 5.2.4 on 2026-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_merge_inventory_duplicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
