# Generated by Django 5.2.4 on 2026-04-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_alter_inventory_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.inventory",
            ),
        ),
    ]
