# Generated by Django 5.2.4 on 2026-04-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_merge_0046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="rent_per_day",
        ),
        migrations.RemoveField(
            model_name="item",
            name="item_name",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="total_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.inventory"
            ),
        ),
    ]
