# Generated by Django 5.2.4 on 2026-04-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_inventory_rent_per_day_remove_item_item_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.inventory",
            ),
        ),
    ]
