# Generated by Django 5.2.4 on 2026-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_alter_item_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="inventory",
        ),
        migrations.AddField(
            model_name="inventory",
            name="rent_per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="item_name",
            field=models.CharField(default="Unknown Item", max_length=255),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="available_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Security deposit amount set by admin",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="total_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
