# Generated by Django 5.2.4 on 2026-04-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_remove_item_inventory_inventory_rent_per_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
