# Generated by Django 5.2.4 on 2026-04-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_alter_item_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(default="Temp Item", max_length=255),
            preserve_default=False,
        ),
    ]
