# Generated by Django 5.2.4 on 2026-04-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_alter_item_item_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="deposit",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="next_available_date",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="rent_per_day",
        ),
    ]
