# Generated by Django 5.2.4 on 2026-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_remove_inventory_deposit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="available_quantity",
        ),
        migrations.AddField(
            model_name="inventory",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="inventory",
            name="next_available_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
