# Generated by Django 5.2.4 on 2026-04-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_remove_inventory_available_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename the existing RentalRequest model to History so data is preserved.
        migrations.RenameModel(old_name='RentalRequest', new_name='History'),
        migrations.AlterField(
            model_name="payment",
            name="rental_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="app.history",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="rental_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="app.history",
            ),
        ),
    ]
