# Generated by Django 5.2.4 on 2026-04-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_history_alter_payment_rental_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="rental_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentalrequest_set",
                to="app.inventory",
            ),
        ),
    ]
