# Generated by Django 5.2.7 on 2026-04-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_history_alter_payment_rental_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='rental_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalrequest_set', to='app.inventory'),
        ),
        migrations.CreateModel(
            name='NotifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
    ]
