# Generated by Django 5.2.4 on 2026-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_history_address_history_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="renter_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
