# Generated by Django 5.2.4 on 2026-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_history_renter_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("renter_name", models.CharField(max_length=255)),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
