# Generated by Django 5.2.4 on 2026-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_customer_delete_customercontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
