# Generated by Django 5.2.4 on 2026-04-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_inventory_available_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="booked_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
