# Generated by Django 5.2.4 on 2026-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_inventory_booked_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="deposit_donated",
            field=models.BooleanField(default=False),
        ),
    ]