# Generated by Django 5.2.7 on 2026-05-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_history_rental_item_notifyrequest'),
        ('app', '0062_history_deposit_donated'),
    ]

    operations = [
    ]
