# Generated by Django 5.2.7 on 2026-05-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_merge_20260505_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='app.inventory'),
        ),
    ]
