# Generated by Django 5.2.4 on 2026-05-13 06:22

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_notification_alter_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf']), app.models.validate_id_proof_file_size]),
        ),
    ]
