# Generated by Django 5.2.4 on 2026-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_userdetail_id_proof_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='history',
            name='donation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
