# Generated by Django 5.2.7 on 2026-05-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_history_donation_amount_history_donation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Item name'),
        ),
    ]
