# Generated by Django 5.2.7 on 2026-06-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_inventory_created_at_inventory_donation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
