# Generated by Django 5.2.4 on 2026-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_today_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
