# Generated by Django 5.2.4 on 2026-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_history_is_today_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='is_today_reminder_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
