# Generated by Django 5.2.4 on 2026-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_bookingextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='history',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='history',
            name='is_delivery_paid',
            field=models.BooleanField(default=False),
        ),
    ]
