# Generated by Django 5.2.4 on 2026-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_history_amount_paid_history_amount_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
