# Generated by Django 5.2.4 on 2026-07-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_history_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='id_proof_file',
        ),
    ]
