# Generated by Django 5.2.4 on 2026-07-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_alter_history_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='prescription',
        ),
    ]
