# Generated by Django 5.2.4 on 2026-07-30 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_bloodrequest_prescription_eventvolunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_access_inventory', models.BooleanField(default=False)),
                ('can_manage_blood_requests', models.BooleanField(default=False)),
                ('can_manage_camps', models.BooleanField(default=False)),
                ('can_manage_donors', models.BooleanField(default=False)),
                ('can_manage_volunteers', models.BooleanField(default=False)),
                ('can_manage_services', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=models.CASCADE, related_name='user_assignments', to='app.role')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'role__name'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
