# Generated by Django 5.2.7 on 2026-07-31 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0084_create_role_userrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="assigned_employee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="last_status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="last_status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blood_requests_status_changed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="status_history",
            field=models.TextField(
                blank=True, help_text="JSON-like status history timeline", null=True
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="units_required",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Assigned", "Assigned"),
                    ("Searching", "Searching"),
                    ("Blood Available", "Blood Available"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Received", "Received"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
