# Generated by Django 5.2.7 on 2026-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_supportservice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportservicecontact',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
