# Generated by Django 5.2.7 on 2026-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_bloodbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_component',
            field=models.CharField(blank=True, choices=[('Whole Blood', 'Whole Blood'), ('Packed Red Blood Cells (PRBC)', 'Packed Red Blood Cells (PRBC)'), ('Platelets', 'Platelets'), ('Fresh Frozen Plasma (FFP)', 'Fresh Frozen Plasma (FFP)'), ('Plasma', 'Plasma'), ('Cryoprecipitate', 'Cryoprecipitate'), ('Single Donor Platelets (SDP)', 'Single Donor Platelets (SDP)'), ('Random Donor Platelets (RDP)', 'Random Donor Platelets (RDP)')], default='Whole Blood', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Assigned', 'Assigned'), ('Searching', 'Searching'), ('Blood Available', 'Blood Available'), ('Ready for Pickup', 'Ready for Pickup'), ('Received', 'Received'), ('Fulfilled', 'Fulfilled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
