# Generated by Django 5.2.7 on 2026-08-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_alter_bloodrequest_blood_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rent (per day)'),
        ),
    ]
