# Generated by Django 5.2.4 on 2026-08-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_history_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('BB', 'BB'), ("Don't Know", "Don't Know")], max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_component',
            field=models.CharField(blank=True, choices=[('PLASMA (C.C.P)', 'PLASMA (C.C.P)'), ('PLASMA (F.F.P)', 'PLASMA (F.F.P)'), ('PCV/PRBC', 'PCV/PRBC'), ('Whole Blood (W.B.)', 'Whole Blood (W.B.)'), ('Platelets (PLT.)', 'Platelets (PLT.)'), ('SDP', 'SDP'), ('RDP', 'RDP'), ('Cryoprecipitate (CYRO.)', 'Cryoprecipitate (CYRO.)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('BB', 'BB'), ("Don't Know", "Don't Know")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='camporganizer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Fulfilled', 'Fulfilled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
