# Generated by Django 5.2.7 on 2026-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0097_alter_bloodrequest_blood_component_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for cancellation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="camporganizer",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
