# Generated by Django 5.2.7 on 2026-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0098_bloodrequest_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
