# Generated by Django 5.2.7 on 2026-08-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0098_blooddonor_full_name_alter_blooddonor_first_name_and_more"),
        ("app", "0099_bloodrequest_request_id"),
    ]

    operations = []
