# Generated by Django 5.2.7 on 2026-08-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_alter_bloodrequest_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blooddonor',
            name='last_name',
        ),
    ]
