# Generated by Django 5.2.7 on 2026-09-01 10:27

from django.db import migrations, models


def alter_columns_if_postgres(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE app_blooddonor ALTER COLUMN blood_group TYPE varchar(20);")
            cursor.execute("ALTER TABLE app_bloodrequest ALTER COLUMN blood_group TYPE varchar(20);")

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0102_remove_blooddonor_first_name_and_more"),
    ]

    operations = [
        migrations.RunPython(alter_columns_if_postgres, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="blooddonor",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("BB", "BB"),
                    ("Don't Know", "Don't Know"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("BB", "BB"),
                    ("Don't Know", "Don't Know"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
