# Generated by Django 5.2.7 on 2026-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0102_remove_blooddonor_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("BB", "BB"),
                    ("Don't Know", "Don't Know"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
